-- Prosody config for CUA agent ↔ phone user messaging
-- No federation (s2s disabled), self-signed certs, internal use

---------- Server-wide settings ----------

admins = {}

-- Modules
modules_enabled = {
    -- Core
    "roster";
    "saslauth";
    "tls";
    "disco";
    "carbons";
    "pep";
    "private";
    "vcard_legacy";
    "version";
    "uptime";
    "time";
    "ping";

    -- Message handling
    "blocklist";
    "smacks";         -- Stream Management (handles flaky mobile connections)
    "csi_simple";     -- Client State Indication (battery-friendly for phones)
    "mam";            -- Message Archive Management (offline message history)

    -- HTTP services
    "http";
    "bosh";
    "websocket";
}

modules_disabled = {
    "s2s";    -- no federation needed
    "posix";  -- breaks in containers (PID/daemonize not needed with -F)
}

-- Running in a container — don't try to daemonize
daemonize = false

-- Disable open registration
allow_registration = false

-- Authentication
authentication = "internal_hashed"

-- TLS — will use self-signed certs generated at startup
-- The CUA connects internally and can skip verification.
-- The phone client will prompt to trust on first connect.
c2s_require_encryption = true

-- Listen on all interfaces (important in containers)
c2s_interfaces = { "*" }
c2s_ports = { 5222 }

-- Message archiving — so the phone gets messages sent while it was offline
archive_expires_after = "1w"
default_archive_policy = true

-- HTTP ports
http_ports = { 5280 }
http_interfaces = { "*" }
https_ports = {}  -- disable HTTPS port; TLS handled by XMPP layer or reverse proxy

-- Accept HTTP requests regardless of Host header.
-- Phones will connect via the host's IP address, not cua.local.
http_default_host = "cua.local"

-- Limits
limits = {
    c2s = { rate = "10kb/s"; burst = "50kb" };
}

---------- Virtual hosts ----------

-- The domain must match XMPP_JID domain used by accounts
VirtualHost "cua.local"
    -- Certs will be generated by entrypoint.sh
    ssl = {
        key = "/etc/prosody/certs/cua.local.key";
        certificate = "/etc/prosody/certs/cua.local.crt";
    }

---------- Components ----------

-- HTTP File Upload (optional — lets the phone user send images to the agent)
Component "upload.cua.local" "http_file_share"
    http_file_share_size_limit = 10485760  -- 10 MB
    http_file_share_expires_after = 86400  -- 1 day
    http_host = "cua.local"
